POST http://localhost:3000/register 
Content-Type: application/json

{
  "username": "adam_hjthgcsd",
  "name": "A",
  "password": "ri",
  "gender": "male",
  "location": "Detroit"
} 

### 
POST http://localhost:3000/login 
Content-Type: application/json 

{
  "username": "adam_richard",
  "password": "richard_567"
} 

### 

PUT http://localhost:3000/change-password 
Content-Type: application/json 

{
  "username": "adam_richard",
  "oldPassword": "ar7",
  "newPassword": "a123"
}